services:
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    env_file:
      - ./agent/.env.local
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
      #- ./frontend:/app
      #- ./frontend/.env.local:/app/.env.local
    environment:
      - NODE_ENV=production
    depends_on:
      - agent
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge